import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
df = pd.read_csv("W1D3-data-loading-cleaning/data/raw_data.csv")
print("load dataset:\n",df.head())
print("\nmissing values:")
df1=df.isnull().sum()
print(df1)
print("Salary Distribution chart:\n")
plt.figure(figsize=(8,5))
plt.hist(df["Salary"],bins=5,edgecolor="black")
plt.title("Salary Distribution")
plt.xlabel("Salary")
plt.ylabel("number of employees")
plt.tight_layout()
plt.savefig("W1D5-data-visualization/outputs/salary_distribution.png")
plt.show()
print("Employees by department:\n\n")
plt.figure(figsize=(8,5))
df['Department'].value_counts().plot(kind="bar")
plt.title("Employees by department")
plt.xlabel("Department")
plt.ylabel("number of employees")
plt.tight_layout()
plt.savefig("W1D5-data-visualization/outputs/department_counts.png")
plt.show()
print("\n age vs salary:\n")
plt.figure(figsize=(8,5))
sns.scatterplot(data=df,x="Age",y="Salary")
plt.title("Age vs Salary")
plt.xlabel("Age")
plt.ylabel("Salary")
plt.tight_layout()
plt.savefig("W1D5-data-visualization/outputs/age_vs_salary.png")
plt.show()
print("\ncorrelation heatmap:\n")
plt.figure(figsize=(8,5))
numeric_data=df.select_dtypes(include="number")
sns.heatmap(numeric_data.corr(),annot=True)
plt.title("correlation heatmap")
plt.tight_layout()
plt.savefig("W1D5-data-visualization/outputs/correlation_heatmap.png")
plt.show()
print("\n all visualizations are created successfully!!!")
