import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.feature_selection import SelectKBest, f_classif
df=pd.read_csv("../W1D3-data-loading-cleaning/data/raw_data.csv")
print("\n print df:", df.head())
print("\n Dataset informstion:", df.info())
df1=df.isnull().sum()
print("\nmissing values:",df1)
df2=df.columns.to_list()
print("\n columns names:",df2)
print("\n\n LABEL ENCODING!!!!!!!\n\n")
Label_encoder=LabelEncoder()
df["Department_Label"]=Label_encoder.fit_transform(df["Department"])
print("encoding the label:\n",df[["Department","Department_Label"]])
print("\n\n ONE-HOT ENCODING!!!!!!!\n\n")
one_hot_encoder=OneHotEncoder(sparse_output=False,handle_unknown="ignore")
city_enocded=one_hot_encoder.fit_transform(df[["City"]])
city_columns=one_hot_encoder.get_feature_names_out(["City"])
city_encoded_df=pd.DataFrame(city_enocded,columns=city_columns)
print("\none hot encoding:\n",city_encoded_df)
print("\n\n ORIGINAL ENCODING!!!!!!!\n\n")
original_encoder=OrdinalEncoder(handle_unknown="use_encoded_value",unknown_value=-1)
department_ordinal=original_encoder.fit_transform(df[["Department"]])
df["Department_ordinal"]=department_ordinal
print("\n\nordinal encoding:\n",df[["Department","Department_ordinal"]])
print("\n\n MISSING VALUE HANDLING!!!!!!!\n\n")
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Salary"] = df["Salary"].fillna(df["Salary"].median())
print("Missing values after filling:")
print(df[["Age", "Salary"]].isnull().sum())
print("\n\n SCALING!!!!!!!\n\n")
numeric_data=df[["Age","Salary"]]
print("\n STANDARD SCALER!!!!!!!\n\n")
standard_scaler=StandardScaler()
standard_scaled=standard_scaler.fit_transform(numeric_data)
standard_scaled_df=pd.DataFrame(standard_scaled,columns=["Age","Salary"])
print("\nstandard scaler:\n",standard_scaled_df)
print("\n MINMAX SCALER!!!!!!!\n\n")
minmax_scaler=MinMaxScaler()
minmax_scaled=minmax_scaler.fit_transform(numeric_data)
minmax_scaled_df=pd.DataFrame(minmax_scaled,columns=["Age","Salary"])
print("\nminmax scaler:\n",minmax_scaled_df)
print("\n ROBUST SCALER!!!!!!!\n\n")
robust_scaler=RobustScaler()
robust_scaled=robust_scaler.fit_transform(numeric_data)
robust_scaled_df=pd.DataFrame(robust_scaled, columns=["Age","Salary"])
print("\nrobust scaler:\n",robust_scaled_df)
print("\n\n PLOTTING DISTRIBUTIONS!!!!!!!\n\n")
plt.figure()
plt.hist(df["Age"], bins=5)
plt.title("Age Before Scaling")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.savefig("age_before_scaling.png")
plt.show()
plt.figure()
plt.hist(df["Salary"], bins=5)
plt.title("Salary Before Scaling")
plt.xlabel("Salary")
plt.ylabel("Frequency")
plt.savefig("salary_before_scaling.png")
plt.show()
plt.figure()
plt.hist(standard_scaled_df["Age"], bins=5)
plt.title("Age After Standard Scaling")
plt.xlabel("Scaled Age")
plt.ylabel("Frequency")
plt.savefig("age_standard_scaled.png")
plt.show()
plt.figure()
plt.hist(standard_scaled_df["Salary"], bins=5)
plt.title("Salary After Standard Scaling")
plt.xlabel("Scaled Salary")
plt.ylabel("Frequency")
plt.savefig("salary_standard_scaled.png")
plt.show()
plt.figure()
plt.hist(minmax_scaled_df["Age"], bins=5)
plt.title("Age After MinMax Scaling")
plt.xlabel("Scaled Age")
plt.ylabel("Frequency")
plt.savefig("age_minmax_scaled.png")
plt.show()
plt.figure()
plt.hist(minmax_scaled_df["Salary"], bins=5)
plt.title("Salary After MinMax Scaling")
plt.xlabel("Scaled Salary")
plt.ylabel("Frequency")
plt.savefig("salary_minmax_scaled.png")
plt.show()
plt.figure()
plt.hist(robust_scaled_df["Age"], bins=5)
plt.title("Age After Robust Scaling")
plt.xlabel("Scaled Age")
plt.ylabel("Frequency")
plt.savefig("age_robust_scaled.png")
plt.show()
plt.figure()
plt.hist(robust_scaled_df["Salary"], bins=5)
plt.title("Salary After Robust Scaling")
plt.xlabel("Scaled Salary")
plt.ylabel("Frequency")
plt.savefig("salary_robust_scaled.png")
plt.show()
print("\n\n SELECTKBEST!!!!!!!\n\n")
features=df[["Age","Salary","Department_Label"]]
target=df["Department_Label"]
select_k_best=SelectKBest(score_func=f_classif,k="all")
selected_features=select_k_best.fit_transform(features,target)
feature_scores=pd.DataFrame({"Feature":features.columns,"Score":select_k_best.scores_})
feature_scores=feature_scores.sort_values(by="Score",ascending=False)
print("\nFeature scores:")
print(feature_scores)
print("\nTop features:")
print(feature_scores.head(5))