import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')
df = pd.read_csv("W1D3-data-loading-cleaning/data/raw_data.csv")
print("first 5 rows:\n")
print(df.head())
print("\n Dataset Information:")
print(df.info())
print("\ncolumns:", df.columns)
print("\ndata types:",df.dtypes)
print("\ndescribe the info:", df.describe)
print("\ndrop dept column:",df.drop(['Department'],axis=1))
df1=df[['Age','Salary']].copy()
print("\ndata copied:",df1)
print("\nrename columns:")
print(df.rename(columns={'Name':'NAME'}))
df2 = df.loc[df.duplicated(subset=['City'])]
print(df2)
df3=df.query('City=="Bangalore"')
print("\nquering:", df3)
df4=df.duplicated(subset=['Name','Age','City']).sum()
print("\nduplicated:\n",df4)
df5=~df.duplicated(subset=['Name','Age','City']).sum()
print("\nduplicated inverse:\n",df5)
print("\n missing values:",df.isnull().sum())
print("\n PLOTTING GRAPHS???????:\n\n")
df[['Age','Salary']].hist(figsize=(10,5))
plt.suptitle("Distributuion of numeric colums:\n")
plt.tight_layout()
plt.show()
df5=df['Salary'].value_counts()
print("\ncounting vlues:\n", df5)
plt.scatter(x='Name',y='Department')
plt.show()
plt.figure(figsize=(6,4))
correlation=df[["Age","Salary"]].corr()
sns.heatmap(correlation,annot=True,cmap="Blues")
plt.title("correlation heatmap")
plt.tight_layout()
plt.show()
plt.savefig("W1D4-eda/outputs/numeric_distributions.png")
plt.savefig("W1D4-eda/outputs/age_salary_scatter.png")
plt.savefig("W1D4-eda/outputs/correlation_heatmap.png")
